---
#On jenkins master node:
- name: To install java and jenkins on jenkins master
  hosts: jenkins
  become: true
  tasks: 
    - name: installing the packages on jenkins-master
      script: jenkins.sh

    - name: updating the task work
      debug:
        msg: "packages had been installed successfully on jenkins-master"

#on docker node:
- name: To install docker on docker server
  hosts: docker
  become: true
  tasks: 
    - name: installing the packages 
      script: docker.sh

    - name: updating the task work
      debug:
        msg: "packages had been installed successfully on docker server"

#on prod-server node:
- name: To install k8s on prod-server
  hosts: k8s
  become: true
  tasks: 
    - name: installing the packages on prod-server
      script: k8s.sh

    - name: updating the task work
      debug:
        msg: "packages had been installed successfully on prod-server"

#the end:
